### ISSUE TITLE
CURL Error with version 0.5.0

### ISSUE THREAD

**Issue by Sonblind** [croaky/parity#23]
Error
-------
When executing `development restore production`, I get an error with parity `0.5.0`:
```
 !    Resource not found

curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
pg_restore: [archiver] input file is too short (read 0, expected 5)
```

Specs
------

Curl `7.37.1`
Ruby `2.2.1p85`

Parity `0.4` is working...

**Comment by geoffharcourt** [comment]
@sonblind, which command and args are you using?

**Comment by Sonblind** [comment]
I'm running: `development restore production`

**Comment by geoffharcourt** [comment]
OK, now that I've uninstalled the shims from homebrew and am running Parity 0.5.0, I'm getting the same error. I'm looking into it.

**Comment by Narzerus** [comment]
Same here

**Comment by croaky** [comment]
Possibly fixed by https://github.com/croaky/parity/commit/89be4ad97253f74c7fb66fa84a655e5710bcffb1 ?

We might want to release 0.5.1

**Comment by geoffharcourt** [comment]
@croaky, 89be4ad doesn't resolve the problem, so hold off on 0.5.1 for the moment. I have some time to look at it now.

**Comment by Narzerus** [comment]
I can't do backups either

**Comment by geoffharcourt** [comment]
I think we broke in 5e789c328040491b3dec7436bdc48f31dbf7c618, when I use those commands directly at the command line they don't work.

**Comment by geoffharcourt** [comment]
According to Heroku's [docs](https://devcenter.heroku.com/articles/mapping-pgbackups-commands), the command new `pg:backups` subcommand `heroku pg:backups public-url` should yield the URL for the last backup, but if you run the command with the `--app appname` or `--remote remotename` switches, you get the reported error about the resource not being found.

I think we should revert 5e789c3, file an issue with Heroku about the toolbelt and/or `pg` command, and then reintroduce it after the issue is resolved with the toolbelt. In the interim, we should release 0.5.1 with the reversion so that users who upgraded to 5.x aren't stranded without what is likely the most-used functionality of parity.

**Comment by croaky** [comment]
@geoffharcourt How does https://github.com/croaky/parity/pull/26 look?

**Comment by croaky** [comment]
Fixed in 0.5.1

https://github.com/croaky/parity/releases/tag/v0.5.1

**Comment by JuanitoFatas** [comment]
:clap: Thanks @croaky and everyone!

**Comment by Sonblind** [comment]
Great fix! Thanks @croaky and team! :+1:

**Comment by srt32** [comment]
I'm seeing this issue when I run `development restore staging` on version `0.5.1`. Was there something I needed to update on my end to apply the fix?

**Comment by geoffharcourt** [comment]
@srt32, Did you install the Homebrew package? I found I wasn't using the version from the Gem which led to some confusing debugging when issues came up with 0.5.0.

**Comment by srt32** [comment]
@geoffharcourt thanks for the idea! I installed it via the gem. I tried uninstalling the gem and reinstalling but I see the same issue.

**Comment by geoffharcourt** [comment]
OK, just for my own sanity (because I had some similar issues with 0.5.0), what version of Heroku toolbelt do you have, and can you confirm that `which production` is using the Rubygem version, and that you don't have any old versions of parity installed? 

I had a project using a different version of Ruby, and with rbenv shims I had issues with which gem version was being used by the executable.

**Comment by srt32** [comment]
`heroku version` yields `heroku-toolbelt/3.30.6 (x86_64-darwin10.8.0) ruby/1.9.3` (the Ruby version looks odd).

`which production` yields `/Users/simon/.rbenv/shims/production`. Maybe I've got some shim crossed up somewhere, like you mentioned.

**Comment by croaky** [comment]
```
rm /Users/simon/.rbenv/shims/production
rm /Users/simon/.rbenv/shims/staging
gem uninstall parity
brew update && brew install parity
```
